# Generated by Django 3.0.3 on 2020-05-08 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=45, null=True)),
                ('website', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('publisher', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(max_length=45, null=True)),
                ('url', models.CharField(max_length=400, null=True)),
                ('cover', models.CharField(max_length=400, null=True)),
                ('introduce', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20, unique=True)),
                ('userPasswd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=255, unique=True)),
                ('cover', models.ImageField(upload_to='series_cover/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20, unique=True)),
                ('userPasswd', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
                ('scores', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user_action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45, null=True)),
                ('action', models.CharField(max_length=45)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.User')),
            ],
            options={
                'db_table': 'user_action',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='book',
            field=models.ManyToManyField(through='wx.user_action', to='wx.books'),
        ),
        migrations.CreateModel(
            name='upload_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=45, null=True)),
                ('website', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('publisher', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(max_length=45, null=True)),
                ('url', models.CharField(max_length=400, null=True)),
                ('cover', models.CharField(max_length=400, null=True)),
                ('status', models.CharField(max_length=45, null=True)),
                ('introduce', models.TextField(null=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.User')),
            ],
        ),
        migrations.CreateModel(
            name='recommend_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=255, unique=True)),
                ('isbn', models.CharField(max_length=45, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('introduce', models.TextField(null=True)),
                ('cover', models.ImageField(upload_to='recommend_cover/')),
                ('url', models.ImageField(upload_to='recommend_url/')),
                ('series_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.series')),
            ],
        ),
    ]
