# Generated by Django 3.0.3 on 2020-05-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_action',
            unique_together={('user', 'books')},
        ),
    ]
