# Generated by Django 3.0.3 on 2020-04-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_books',
            name='status',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='scores',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_action',
            name='type',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
