# Generated by Django 3.0.3 on 2020-04-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0002_auto_20200418_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recommand_books',
            new_name='recommend_books',
        ),
    ]
