# Generated by Django 3.0.3 on 2020-04-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0003_auto_20200419_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend_books',
            name='url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='recommend_books',
            name='cover',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='recommend_books',
            name='introduce',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='cover',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
