# Generated by Django 3.0.3 on 2020-04-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0005_auto_20200424_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend_books',
            name='cover',
            field=models.ImageField(null=True, upload_to='recommend_cover/'),
        ),
        migrations.AlterField(
            model_name='recommend_books',
            name='url',
            field=models.ImageField(null=True, upload_to='recommend_url/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='cover',
            field=models.ImageField(null=True, upload_to='series_cover/'),
        ),
    ]
