# Generated by Django 3.0.3 on 2020-03-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=45, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('publisher', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(max_length=45, null=True)),
                ('url', models.CharField(max_length=400, null=True)),
                ('cover', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
