# Generated by Django 3.0.3 on 2020-03-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='website',
            field=models.CharField(default='libgen.lc', max_length=200, null=True),
        ),
    ]
