# Generated by Django 3.0.3 on 2020-04-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0002_books_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
